In [1]:
import tensorflow as tf

2024-06-02 18:47:44.803699: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-02 18:47:45.388062: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-02 18:47:45.391629: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-02 18:47:46.782790: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
import numpy as np

dtype = tf.float16 # subject to change
BASE_DIR = "/home/kernal1/QM_Sandbox/Phi_2/phi_local/weights/"
# DECODER_LAYERS = 3 # PUT BACK IN
DECODER_LAYERS = 3  # REMOVE
params = {}
params['embed_tokens'] = tf.constant(np.load(BASE_DIR + 'embed_tokens.npy'), dtype=dtype)
params['decoder_layers'] = []

for i in range(DECODER_LAYERS):
  layer_params = {}
  layer_params['layernorm_weight'] = 'layernorm_weight.npy'
  layer_params['layernorm_bias'] = 'layernorm_bias'
  layer_params['q_proj_weight'] = 'q_proj_weight'
  layer_params['q_proj_bias'] = 'q_proj_bias'
  layer_params['k_proj_weight'] = 'k_proj_weight'
  layer_params['k_proj_bias'] = 'k_proj_bias'
  layer_params['v_proj_weight'] = 'v_proj_weight'
  layer_params['v_proj_bias'] = 'v_proj_bias'
  layer_params['dense_weight'] = 'dense_weight'
  layer_params['dense_bias'] = 'dense_bias'
  layer_params['mlp_fc1_weight'] = 'mlp_fc1_weight'
  layer_params['mlp_fc1_bias'] = 'mlp_fc1_bias'
  layer_params['mlp_fc2_weight'] = 'mlp_fc2_weight'
  layer_params['mlp_fc2_bias'] = 'mlp_fc2_bias'
  for key in layer_params:
    layer_params[key] = tf.constant(np.load(BASE_DIR + str(i) + '_' + key + '.npy'), dtype=dtype)
    if "weight" in key and "layernorm" not in key:
      layer_params[key] = tf.transpose(layer_params[key], perm=[1,0])
    print(key, ": ", layer_params[key].shape) # remove later
  params['decoder_layers'].append(layer_params)

params['final_layernorm_weight'] = tf.constant(np.load(BASE_DIR + 'final_layernorm_weight.npy'), dtype=dtype)
params['final_layernorm_bias'] = tf.constant(np.load(BASE_DIR + 'final_layernorm_bias.npy'), dtype=dtype)

params['lm_head_weight'] = tf.transpose(tf.constant(np.load(BASE_DIR + 'lm_head_weight.npy'), dtype=dtype), perm=[1,0])
params['lm_head_bias'] = tf.constant(np.load(BASE_DIR + 'lm_head_bias.npy'), dtype=dtype)

2024-06-02 18:47:49.696862: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-06-02 18:47:49.698501: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


layernorm_weight :  (2560,)
layernorm_bias :  (2560,)
q_proj_weight :  (2560, 2560)
q_proj_bias :  (2560,)
k_proj_weight :  (2560, 2560)
k_proj_bias :  (2560,)
v_proj_weight :  (2560, 2560)
v_proj_bias :  (2560,)
dense_weight :  (2560, 2560)
dense_bias :  (2560,)
mlp_fc1_weight :  (2560, 10240)
mlp_fc1_bias :  (10240,)
mlp_fc2_weight :  (10240, 2560)
mlp_fc2_bias :  (2560,)
layernorm_weight :  (2560,)
layernorm_bias :  (2560,)
q_proj_weight :  (2560, 2560)
q_proj_bias :  (2560,)
k_proj_weight :  (2560, 2560)
k_proj_bias :  (2560,)
v_proj_weight :  (2560, 2560)
v_proj_bias :  (2560,)
dense_weight :  (2560, 2560)
dense_bias :  (2560,)
mlp_fc1_weight :  (2560, 10240)
mlp_fc1_bias :  (10240,)
mlp_fc2_weight :  (10240, 2560)
mlp_fc2_bias :  (2560,)
layernorm_weight :  (2560,)
layernorm_bias :  (2560,)
q_proj_weight :  (2560, 2560)
q_proj_bias :  (2560,)
k_proj_weight :  (2560, 2560)
k_proj_bias :  (2560,)
v_proj_weight :  (2560, 2560)
v_proj_bias :  (2560,)
dense_weight :  (2560, 2560)
dens

In [3]:
# import numpy as np

# params['embed_tokens'].numpy().tofile('embed_tokens.dat')

# x = None
# y = None

# # tf.reshape(params['final_layernorm_weight'], [2560])
# # params['lm_head_weight']
# # params['lm_head_bias']
# y = tf.concat([
#     tf.reshape(params['final_layernorm_weight'], [2560]),
#     tf.reshape(params['final_layernorm_bias'], [2560]),
#     tf.reshape(params['lm_head_weight'], [2560*51200]),
#     tf.reshape(params['lm_head_bias'], [51200])
# ], axis=-1)

# y.numpy().tofile('lm_head_weights_1.dat')

# layer_params = params['decoder_layers']


# x = tf.concat([
#         tf.reshape(layer_params[0]['layernorm_weight'], [2560]),
#         tf.reshape(layer_params[0]['layernorm_bias'], [2560]),
#         tf.reshape(layer_params[0]['q_proj_weight'], [2560 * 2560]),
#         tf.reshape(layer_params[0]['q_proj_bias'], [2560]),
#         tf.reshape(layer_params[0]['k_proj_weight'], [2560 * 2560]),
#         tf.reshape(layer_params[0]['k_proj_bias'], [2560]),
#         tf.reshape(layer_params[0]['v_proj_weight'], [2560 * 2560]),
#         tf.reshape(layer_params[0]['v_proj_bias'], [2560]),
#         tf.reshape(layer_params[0]['dense_weight'], [2560 * 2560]),
#         tf.reshape(layer_params[0]['dense_bias'], [2560]),
#         tf.reshape(layer_params[0]['mlp_fc1_weight'], [2560 * 10240]),
#         tf.reshape(layer_params[0]['mlp_fc1_bias'], [10240]),
#         tf.reshape(layer_params[0]['mlp_fc2_weight'], [10240 * 2560]),
#         tf.reshape(layer_params[0]['mlp_fc2_bias'], [2560]),
#         ], axis=-1)

# for i in range(1, DECODER_LAYERS):
#     print(i)
#     x = tf.concat([x, 
#         tf.reshape(layer_params[i]['layernorm_weight'], [2560]),
#         tf.reshape(layer_params[i]['layernorm_bias'], [2560]),
#         tf.reshape(layer_params[i]['q_proj_weight'], [2560 * 2560]),
#         tf.reshape(layer_params[i]['q_proj_bias'], [2560]),
#         tf.reshape(layer_params[i]['k_proj_weight'], [2560 * 2560]),
#         tf.reshape(layer_params[i]['k_proj_bias'], [2560]),
#         tf.reshape(layer_params[i]['v_proj_weight'], [2560 * 2560]),
#         tf.reshape(layer_params[i]['v_proj_bias'], [2560]),
#         tf.reshape(layer_params[i]['dense_weight'], [2560 * 2560]),
#         tf.reshape(layer_params[i]['dense_bias'], [2560]),
#         tf.reshape(layer_params[i]['mlp_fc1_weight'], [2560 * 10240]),
#         tf.reshape(layer_params[i]['mlp_fc1_bias'], [10240]),
#         tf.reshape(layer_params[i]['mlp_fc2_weight'], [10240 * 2560]),
#         tf.reshape(layer_params[i]['mlp_fc2_bias'], [2560]),
#         ], axis=-1)


# x.numpy().tofile('decoder_weights_1.dat') # careful


In [4]:
class PhiConfig():
    keys_to_ignore_at_inference = ["past_key_values"]
    def __init__(
        self,
        vocab_size=51200,
        hidden_size=2560,
        intermediate_size=10240,
        num_hidden_layers=DECODER_LAYERS, # modified,
        num_attention_heads=32,
        num_key_value_heads=32,
        resid_pdrop=0.0, # the model bt default has 0.1 on colab, but we dont have randomness
        embd_pdrop=0.0,
        attention_dropout=0.0,
        hidden_act="gelu_new",
        max_position_embeddings=2048,
        initializer_range=0.00,
        layer_norm_eps=1e-5,
        use_cache=True,                  # Modifed
        tie_word_embeddings=False,
        rope_theta=10000.0,
        rope_scaling=None,
        partial_rotary_factor=0.4,
        qk_layernorm=False,
        bos_token_id=50256,
        eos_token_id=50256,
    ):
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads

        if num_key_value_heads is None:
            num_key_value_heads = num_attention_heads

        self.num_key_value_heads = num_key_value_heads
        self.resid_pdrop = resid_pdrop
        self.embd_pdrop = embd_pdrop
        self.attention_dropout = attention_dropout
        self.hidden_act = hidden_act
        self.max_position_embeddings = max_position_embeddings
        self.initializer_range = initializer_range
        self.layer_norm_eps = layer_norm_eps
        self.use_cache = use_cache
        self.rope_theta = rope_theta
        self.rope_scaling = rope_scaling
        self.partial_rotary_factor = partial_rotary_factor
        self.qk_layernorm = qk_layernorm
        self.pad_token_id = None
        self._attn_implementation = 'eager'

In [5]:
import my_phi_gm
config_gm = PhiConfig()
import importlib

In [ ]:
importlib.reload(my_phi_gm)
importlib.reload(my_phi_gm.bert)
importlib.reload(my_phi_gm.masking_utils_gm)
importlib.reload(my_phi_gm.cache)
config_gm = PhiConfig(use_cache=True)
my_model_gm = None
my_model_gm = my_phi_gm.PhiForCausalLM(config_gm, params)
# testing input to see if graphmode works
input_ids_gm = tf.constant([[40, 588, 836, 5500, 13, 1867, 318, 534, 4004, 2057, 30]])
mask_gm = tf.constant([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
model_kwargs_gm = {'use_cache': True, 'attention_mask': mask_gm}
model_inputs_gm = my_model_gm.prepare_inputs_for_generation(input_ids_gm, **model_kwargs_gm)
out_gm = my_model_gm(
        **model_inputs_gm,
        return_dict=False, # important
        output_attentions=False,
        output_hidden_states=False
        )
print(out_gm[0])

In [ ]:
# loop version
importlib.reload(my_phi_gm)
importlib.reload(my_phi_gm.bert)
importlib.reload(my_phi_gm.masking_utils_gm)
importlib.reload(my_phi_gm.cache)
my_model_gm = None
# config = PhiConfig(num_hidden_layers=3) # old line
config_gm = PhiConfig(use_cache=True)
my_model_gm = my_phi_gm.PhiForCausalLM(config_gm, params)

input_ids_gm = tf.constant([[40, 588, 836, 5500, 13, 1867, 318, 534, 4004, 2057, 30]])
mask_gm = tf.constant([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
model_kwargs_gm = {'use_cache': True, 'attention_mask': mask_gm}

# model_inputs(keys) after first call in orginal code: dict_keys(['input_ids', 'position_ids', 'past_key_values', 'use_cache', 'attention_mask'])

# prepare_inputs_for_generation on first run looks good (not sure about 2nd)

for i in range(2):
  # print("model_kwargs:", model_kwargs_gm)
  model_inputs_gm = my_model_gm.prepare_inputs_for_generation(input_ids_gm, **model_kwargs_gm)
  # print("model_inputs", model_inputs_gm)
  # print(model_inputs.keys())
  print("model_inputs[attention_mask]", model_inputs_gm["attention_mask"])
  out = my_model_gm(
          **model_inputs_gm,
          return_dict=False, # important
          output_attentions=False,
          output_hidden_states=False
         )
  print("out length:", len(out))

  print("logits.shape", out[0].shape)
  # print("out.past_key_values[0][0].shape:", out.past_key_values[0][0].shape)
  next_token_logits = out[0][:, -1, :]
  next_tokens = tf.math.argmax(next_token_logits, axis=-1, output_type=tf.int32)
  input_ids_gm = tf.concat([input_ids_gm, next_tokens[:, None]], axis=-1)

  print("\n\n")
  # need to update past_key_values as apart of model_kwargs
  # need to update size of mask (looks like we did, not sure about proper values)
  # past_key_value shape[0][0]: ([1, 32, 11, 80]) after first run of model in orginal code
  attention_mask = model_kwargs_gm["attention_mask"]
  model_kwargs_gm["attention_mask"] = tf.concat([attention_mask, 
                                                 tf.ones((attention_mask.shape[0], 1), 
                                                         dtype=attention_mask.dtype)], 
                                                         axis=-1)
  print("model_kwargs[attention_mask].shape", model_kwargs_gm["attention_mask"].shape)
  model_kwargs_gm["past_key_values"] = out[1]
  # ending stuff

In [ ]:
print(model_inputs_gm)

In [6]:
import my_phi

In [7]:
# eager mode loop
# loop version
importlib.reload(my_phi)
importlib.reload(my_phi.bert)
importlib.reload(my_phi.masking_utils_gm)
importlib.reload(my_phi.cache)
my_model = None
# config = PhiConfig(num_hidden_layers=3) # old line
config = PhiConfig(use_cache=True)
my_model = my_phi.PhiForCausalLM(config, params)

input_ids = tf.constant([[2061, 318, 534, 4004, 3124, 30, 13, 11517, 318, 2266, 13]])
mask = tf.constant([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
model_kwargs = {'use_cache': True, 'attention_mask': mask}

# model_inputs(keys) after first call in orginal code: dict_keys(['input_ids', 'position_ids', 'past_key_values', 'use_cache', 'attention_mask'])

# prepare_inputs_for_generation on first run looks good (not sure about 2nd)

for i in range(2):
  # print("model_kwargs:", model_kwargs)
  model_inputs = my_model.prepare_inputs_for_generation(input_ids, **model_kwargs)
  print("---------\nMODEL_INPUTS:\n", "MASK:" , model_inputs['attention_mask'])
  print("POS_IDS:", model_inputs['position_ids'], "\n\n---------\n")
  # print("model_inputs", model_inputs)
  # print(model_inputs.keys())
  print("model_inputs[attention_mask]", model_inputs["attention_mask"])
  out = my_model(
          **model_inputs,
          return_dict=False, # important
          output_attentions=False,
          output_hidden_states=False
         )
  print("out length:", len(out))

  print("logits.shape", out[0].shape)
  # print("out.past_key_values[0][0].shape:", out.past_key_values[0][0].shape)
  print("----out[0].shape: ", out[0].shape)
  next_token_logits = out[0][:, -1, :]
  next_tokens = tf.math.argmax(next_token_logits, axis=-1, output_type=tf.int32)
  input_ids = tf.concat([input_ids, next_tokens[:, None]], axis=-1)
  
  print("next token predicted: ", next_tokens)
  print("\n\n")
  # need to update past_key_values as apart of model_kwargs
  # need to update size of mask (looks like we did, not sure about proper values)
  # past_key_value shape[0][0]: ([1, 32, 11, 80]) after first run of model in orginal code
  attention_mask = model_kwargs["attention_mask"]
  model_kwargs["attention_mask"] = tf.concat([attention_mask, 
                                                 tf.ones((attention_mask.shape[0], 1), 
                                                         dtype=attention_mask.dtype)], 
                                                         axis=-1)
  print("model_kwargs[attention_mask].shape", model_kwargs["attention_mask"].shape)
  model_kwargs["past_key_values"] = out[1]
  # ending stuff

32 2048 10000.0
initial sin_cos size: (2048, 32)
32 2048 10000.0
initial sin_cos size: (2048, 32)
32 2048 10000.0
initial sin_cos size: (2048, 32)
---------
MODEL_INPUTS:
 MASK: tf.Tensor([[1 1 1 1 1 1 1 1 1 1 1]], shape=(1, 11), dtype=int32)
POS_IDS: tf.Tensor([[ 0  1  2  3  4  5  6  7  8  9 10]], shape=(1, 11), dtype=int32) 

---------

model_inputs[attention_mask] tf.Tensor([[1 1 1 1 1 1 1 1 1 1 1]], shape=(1, 11), dtype=int32)
input_ids.dtype <dtype: 'int32'>
inputs_embeds.dtype <dtype: 'float16'>
after embedding: hidden states shape: (1, 11, 2560)
_______TESTING SIZES____
(1, 11, 2560)
(1, 1, 11, 11)
(1, 11)
position ids:  tf.Tensor([[ 0  1  2  3  4  5  6  7  8  9 10]], shape=(1, 11), dtype=int32)
residual: (1, 11, 2560)
hidden_states.shape:  (1, 11, 2560)
attention_mask.shape:  (1, 1, 11, 11)
position_ids.shape: (1, 11)
attention_mask: tf.Tensor(
[[[[     0. -65504. -65504. -65504. -65504. -65504. -65504. -65504.
    -65504. -65504. -65504.]
   [     0.      0. -65504. -65504. -6

In [ ]:
# testing an actual realistic loop
# eager mode loop

importlib.reload(my_phi)
importlib.reload(my_phi.bert)
importlib.reload(my_phi.masking_utils_gm)
importlib.reload(my_phi.cache)
my_model = None
# config = PhiConfig(num_hidden_layers=3) # old line
config = PhiConfig(use_cache=True)
my_model = my_phi.PhiForCausalLM(config, params)

input_ids = tf.constant([[2061, 318, 534, 4004, 3124, 30, 13, 11517, 318, 2266, 13]])
mask = tf.constant([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
model_kwargs = {'use_cache': True, 'attention_mask': mask}

# model_inputs(keys) after first call in orginal code: dict_keys(['input_ids', 'position_ids', 'past_key_values', 'use_cache', 'attention_mask'])

# prepare_inputs_for_generation on first run looks good (not sure about 2nd)

for i in range(1):
    print("model_kwargs:", model_kwargs)
    model_inputs = my_model.prepare_inputs_for_generation(input_ids, **model_kwargs)
    print("---------\nMODEL_INPUTS:\n", "MASK:" , model_inputs['attention_mask'])
    print("POS_IDS:", model_inputs['position_ids'], "\n\n---------\n")
    # print("model_inputs", model_inputs)
    # print(model_inputs.keys())
    out = my_model(
        **model_inputs,
        return_dict=False, # important
        output_attentions=False,
        output_hidden_states=False
        )
    print("out length:", len(out))
    print("logits.shape", out[0].shape)
    # print("out.past_key_values[0][0].shape:", out.past_key_values[0][0].shape)
    print("----out[0].shape: ", out[0].shape)
    next_token_logits = out[0][:, -1, :]
    next_tokens = tf.math.argmax(next_token_logits, axis=-1, output_type=tf.int32)
    input_ids = tf.concat([input_ids, next_tokens[:, None]], axis=-1)

    print("next token predicted: ", next_tokens)
    print("\n\n")
    # need to update past_key_values as apart of model_kwargs
    # need to update size of mask (looks like we did, not sure about proper values)
    # past_key_value shape[0][0]: ([1, 32, 11, 80]) after first run of model in orginal code
    attention_mask = model_kwargs["attention_mask"]
    model_kwargs["attention_mask"] = tf.concat([attention_mask, tf.ones((attention_mask.shape[0], 1), dtype=attention_mask.dtype)], axis=-1)
    print("model_kwargs[attention_mask].shape", model_kwargs["attention_mask"].shape)
    model_kwargs["past_key_values"] = out[1]
    

In [ ]:
import math

@tf.function
def test(input):
    x = math.sqrt(3)
    return tf.nn.softmax((1 - tf.experimental.numpy.triu(input, k=3)) / x)
    # print(tf.math.reduce_max(input).shape)

@tf.function
def test2(input):
    x1 = test(input)
    print(x1)
    return [[tf.cast(x1, dtype=tf.float16), x1], x1]

@tf.function
def test3(input):
    return 1 + test2(input)[0][1]

@tf.function
def test4(i1, i2):
    if i2 is None:
        i2 = tf.ones([4,4])
    i1 += 2
    return i1, i2

@tf.function
def test5(i1, i2):
    x1, x2 = test4(i1, i2)
    x2 = [tf.ones([4,4]), tf.ones([4,4])]
    x2[0] += 1
    return test4(x1, x2)

@tf.function
def test6(i1):
    i2 = [i[:] for i in i1] # allows us to create a deep copy of a list(list(tensors))
    # i2 = i1[:]
    # print(i2)
    i2[1][0] += i2[1][0]
    return i2

x = [[tf.zeros([4,]),], [tf.ones([4,]),]]
# x = [tf.zeros([4,]),]
out = test6(x)
print(out)
# print(x)
# print(y)